### PR TITLE
Refactor data parsing to use CSV.jl and add tests

### PR DESCRIPTION
**Pull request by odow**
Smaller part of #30.

The data parsing has a lot of potential issues, so let's do them in very small PRs.

@adow031: what is the format of `reservoir_limits.csv`? It's got `MIN_1_LEVEL` and `MIN_1_PENALTY` fields, but there are no examples of reasonable values for them. (I can guess, based on the code, but I don't know if that's a good or bad idea.)

### CODE REVIEW

**Comment by adow031** [comment]
> @adow031: what is the format of `reservoir_limits.csv`? It's got `MIN_1_LEVEL` and `MIN_1_PENALTY` fields, but there are no examples of reasonable values for them. (I can guess, based on the code, but I don't know if that's a good or bad idea.)

I'll email you the file we've been using.

**Comment by odow** [comment]
Okay, how's this?

**Comment by odow** [comment]
Urgh. I found a problem with the `CSV.Rows` approach: some of the data files have trailing comments!?! I don't think the CSV parser can handle these...

**Comment by odow** [comment]
Merging because this is getting a bit long. @adow031 can test off `develop`.

**Pull request merged**
